# Site Settings
title: "iFrame By It Is Unique Official"
description: "Explore cutting-edge news and updates on tech, politics, entertainment, and more, brought to you by It Is Unique Official."
url: "https://itisuniqueofficial.github.io"  # Your site's URL
baseurl: "iframe"  # Use baseurl if your site is hosted in a subdirectory

# Permalink Settings (Custom folder structure)
permalink: /:categories/:title/  # Use :categories for the folder name based on the category of the post

# Pagination Settings
paginate: 5  # Number of posts per page

# SEO and Meta Tags
seo:
  title: "iFrame By It Is Unique Official | {{ page.title }}"
  description: "Explore cutting-edge news and updates on tech, politics, entertainment, and more, brought to you by It Is Unique Official."
  image: "{{ '/assets/images/og-image.png' | asset_path }}"  # Default image for social sharing

# Jekyll Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-minifier
  - jekyll-archives

# Sitemap Configuration
sitemap:
  exclude:
    - '/feed.xml'
    - '/atom.xml'
    - '/assets/*'
    - '/drafts/*'
    - '/node_modules/*'

# RSS Feed Configuration
feed:
  path: "feed.xml"
  title: "iFrame By It Is Unique Official - RSS Feed"
  description: "Stay updated with the latest posts from iFrame By It Is Unique Official."

# Pagination Configuration
paginate_path: "/page:num/"

# Exclude files from processing
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules/*"

# Localization
locale: "en"

# Build Settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
