# Site Settings
title: "iFrame By It Is Unique Official"
description: "Explore cutting-edge news and updates on tech, politics, entertainment, and more, brought to you by It Is Unique Official."
url: "https://itisuniqueofficial.github.io"  # Your site's URL
baseurl: "iframe"  # Use baseurl if your site is hosted in a subdirectory

# Permalink Settings (Custom folder structure)
permalink: /:categories/:title/  # Use :categories for the folder name based on the category of the post

# Pagination Settings
paginate: 5  # Number of posts per page

# SEO and Meta Tags
seo:
  title: "iFrame By It Is Unique Official | {{ page.title }}"  # Dynamic title for SEO purposes
  description: "Explore cutting-edge news and updates on tech, politics, entertainment, and more, brought to you by It Is Unique Official."
  image: "/assets/images/og-image.png"  # Default image for social sharing

# Jekyll Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-feed

# Sitemap Configuration
sitemap:
  exclude:
    - '/feed.xml'  # Exclude feed from sitemap
    - '/atom.xml'
    - '/assets/*'  # Exclude assets
    - '/drafts/*'  # Exclude drafts folder
    - '/node_modules/*'  # Exclude node_modules if applicable

# RSS Feed Configuration
feed:
  path: "feed.xml"  # Path for your RSS feed
  title: "iFrame By It Is Unique Official - RSS Feed"
  description: "Stay updated with the latest posts from iFrame By It Is Unique Official."

# Pagination Configuration
paginate_path: "/page:num/"  # Path for pagination (e.g., /page2/)

# Exclude files from processing
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules/*"  # Exclude node_modules if using front-end libraries

# Localization
locale: "en"  # Site language (optional)

# Build Settings
defaults:
  - scope:
      path: ""  # Applies to root path
    values:
      layout: "default"  # Default layout for posts and pages
